//! Wire protocol shared by the broker server and any client.

use serde::{Deserialize, Serialize};

/// Build the per-launch pipe name from the owner SID and a public,
/// launcher-supplied nonce.
///
/// The nonce — generated by the trusted launcher with a CSPRNG — is what
/// makes the name unpredictable, so a same-user process cannot pre-create
/// ("squat") the pipe to intercept the real client. Crucially the name is
/// derived from the *nonce*, never from the secret capability token, so the
/// named-pipe namespace exposes no function of the token. The launcher hands
/// the same nonce to both the broker and any legitimate client.
pub fn pipe_name_for(owner_sid: &str, pipe_nonce: &str) -> String {
    format!("\\\\.\\pipe\\NGSM-broker-{owner_sid}-{pipe_nonce}")
}

/// A single broker request. `op` selects the handler; `args` is an
/// opaque JSON value the handler interprets.
#[derive(Debug, Clone, Deserialize)]
pub struct Request {
    #[serde(default)]
    pub id: Option<String>,
    /// Per-launch capability token. Every request must carry the exact token
    /// the broker was started with — this, not the pipe DACL alone, is the
    /// broker's primary authorization check, because the DACL grants access
    /// to *every* process running as the owner.
    #[serde(default)]
    pub token: Option<String>,
    pub op: String,
    #[serde(default)]
    pub args: serde_json::Value,
}

/// Broker response. `status` is `"ok"` for success and `"error"` for
/// failure; on success `result` carries the JSON result, on failure
/// `error` carries a human-readable message.
#[derive(Debug, Clone, Serialize)]
pub struct Response {
    pub id: Option<String>,
    pub status: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl Response {
    pub fn ok(id: Option<String>, result: serde_json::Value) -> Self {
        Self {
            id,
            status: "ok",
            result: Some(result),
            error: None,
        }
    }
    pub fn err(id: Option<String>, message: impl Into<String>) -> Self {
        Self {
            id,
            status: "error",
            result: None,
            error: Some(message.into()),
        }
    }
}

/// Constant-time-ish comparison of a presented token against the expected
/// one. Length is allowed to leak; the byte comparison does not short-circuit
/// on the first mismatch.
pub fn token_matches(expected: &str, presented: Option<&str>) -> bool {
    let Some(presented) = presented else {
        return false;
    };
    if expected.len() != presented.len() {
        return false;
    }
    let mut diff = 0u8;
    for (a, b) in expected.bytes().zip(presented.bytes()) {
        diff |= a ^ b;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn token_matches_only_on_exact_value() {
        assert!(token_matches("s3cr3t", Some("s3cr3t")));
        assert!(!token_matches("s3cr3t", Some("S3CR3T")));
        assert!(!token_matches("s3cr3t", Some("s3cr3")));
        assert!(!token_matches("s3cr3t", Some("")));
        assert!(!token_matches("s3cr3t", None));
    }

    #[test]
    fn request_parses_without_optional_fields() {
        let req: Request = serde_json::from_str(r#"{ "op": "ping" }"#).unwrap();
        assert_eq!(req.op, "ping");
        assert!(req.id.is_none());
        assert!(req.token.is_none());
    }

    #[test]
    fn request_carries_token_when_present() {
        let req: Request =
            serde_json::from_str(r#"{ "op": "list", "token": "abc", "id": "1" }"#).unwrap();
        assert_eq!(req.token.as_deref(), Some("abc"));
        assert_eq!(req.id.as_deref(), Some("1"));
    }
}
